setwd("C:/Users/Joseph/prevR/")
remove(list=ls(all=T))
unlink(file.path(Sys.getenv("R_HOME"),"library/prevR"),rec=T)
library(sp)
library(gstat)
library(maptools)
files=dir("./ScriptsDev",full=T,patt=".r")
ind=grep("setClass",files)
#ind2=grep("demo",files)
#package.skeleton("prevR",code_file=c(files[ind],files[-c(ind,ind2)]),namespace =TRUE, force =TRUE)
package.skeleton("prevR",code_file=c(files[ind],files[-ind]),namespace =TRUE, force =TRUE)
dir.create("./prevR/inst/po/fr/LC_MESSAGES",rec=T)
unlink("./prevR/man",rec=T)
dir.create("./prevR/man",rec=T)
#q("no")